# Generated by Django 6.0 on 2025-12-13 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_alter_boardtile_value_int'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='board_length',
            field=models.PositiveSmallIntegerField(default=50, help_text='Number of tiles on the board (including start/finish).'),
        ),
    ]
