# Generated by Django 5.2.7 on 2025-12-21 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_game_enabled_tiles_game_pending_question_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='pending_shop',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
