# Generated by Django 6.0 on 2025-12-13 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_alter_game_board_length'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='pending_question',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
