# Generated by Django 6.0 on 2025-12-14 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0004_game_pending_question'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='enabled_tiles',
            field=models.JSONField(blank=True, default=list, help_text="Board generatsiyasida ishlatiladigan tile turlari (ro'yxat)."),
        ),
    ]
