# Generated by Django 5.2.7 on 2025-12-21 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0004_game_pending_shop'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='pending_duel',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
