# Generated by Django 6.0 on 2025-12-21 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0005_game_pending_duel'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='survival_difficulty',
            field=models.CharField(choices=[('easy', 'Easy'), ('normal', 'Normal'), ('hard', 'Hard')], default='normal', max_length=16),
        ),
        migrations.AlterField(
            model_name='game',
            name='board_length',
            field=models.PositiveSmallIntegerField(default=36, help_text='Number of tiles on the board (including start/finish).'),
        ),
    ]
