# Generated by Django 6.0 on 2025-12-14 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0005_game_enabled_tiles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='enabled_tiles',
            field=models.JSONField(blank=True, default=list, help_text='Which tile types are enabled for board generation (list of strings).'),
        ),
    ]
