# Generated by Django 6.0 on 2025-12-14 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0006_alter_game_enabled_tiles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='enabled_tiles',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
