# Generated by Django 6.0 on 2025-12-15 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0007_alter_game_enabled_tiles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boardtile',
            name='tile_type',
            field=models.CharField(choices=[('start', 'Start'), ('finish', 'Finish'), ('question', 'Question'), ('trap', 'Trap'), ('heal', 'Heal'), ('bonus', 'Bonus'), ('warp', 'Warp'), ('mass_warp', 'Mass Warp'), ('duel', 'Duel'), ('shop', 'Shop'), ('safe', 'Safe')], default='safe', max_length=32),
        ),
    ]
