# Generated by Django 6.0 on 2025-12-17 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0008_alter_boardtile_tile_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='playeringame',
            name='extra_rolls',
            field=models.PositiveSmallIntegerField(default=0, help_text='Extra dice rolls available (from Reroll Dice card).'),
        ),
        migrations.AddField(
            model_name='playeringame',
            name='shield_points',
            field=models.PositiveSmallIntegerField(default=0, help_text='Blocks incoming damage (negative HP deltas) until depleted.'),
        ),
        migrations.AlterField(
            model_name='supportcardtype',
            name='effect_type',
            field=models.CharField(choices=[('move_extra', 'Move extra cells'), ('heal', 'Heal HP'), ('shield', 'Damage shield'), ('reroll', 'Reroll dice'), ('swap_position', 'Swap position with another player'), ('change_question', 'Change question'), ('custom', 'Custom effect'), ('bonus_coin', 'Bonus coin')], default='custom', max_length=32),
        ),
    ]
