# Generated by Django 6.0 on 2026-01-07 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0008_playeringame_draft_options_playeringame_draft_picks_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='pending_gun',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='boardtile',
            name='tile_type',
            field=models.CharField(choices=[('start', 'Start'), ('finish', 'Finish'), ('question', 'Question'), ('trap', 'Trap'), ('heal', 'Heal'), ('bonus', 'Bonus'), ('gun', 'Gun'), ('warp', 'Warp'), ('mass_warp', 'Mass Warp'), ('duel', 'Duel'), ('shop', 'Shop'), ('safe', 'Safe'), ('portal', 'Portal')], default='safe', max_length=32),
        ),
        migrations.AlterField(
            model_name='game',
            name='mode',
            field=models.CharField(choices=[('finish', 'Custom Game'), ('draft', 'Draft Mode'), ('survival', 'Survival')], default='finish', max_length=16),
        ),
    ]
